StackedQueue: 
	g++ Node.cpp Stack.cpp StackedQueue.cpp main.cpp -o ../out/StackedQueue

SortStack:
	g++ Node.cpp Stack.cpp SortStack.cpp main.cpp -o ../out/SortStack

StackMin:
	g++ Node.cpp Stack.cpp SetOfStack.cpp main.cpp -o ../out/SetOfStacks
